### ISSUE TITLE
some way to tell if the file is a symbolic link with ssh_scp_request_get_permissions or another function

### ISSUE THREAD

**Issue by insinfo** [ShiftMediaProject/libssh#5]
some way to tell if the file is a symbolic link with ssh_scp_request_get_permissions or another function?

I'm currently using this libssh in an open source project I'm developing, a linux server backup system, which runs on windows with Flutter, I made a dart ffi binding with this lib and it works fine. but I end up copying everything with the scp function even the files and folders with symbolic link, I wanted to ignore the files with symbolic link, for that I needed a function to return the permission string that has the first character that defines if it is directory, file or symbolic link.

This permission **lrwxrwxrwx** => is a symbolic link as it starts with the letter 'L'

```dart
var scp = ssh_scp_new(
        session, SSH_SCP_READ | SSH_SCP_RECURSIVE, remoteDirectoryPath);
    if (scp == nullptr) {
      throw Exception(
          'Error allocating scp directory session: ${ssh_get_error(session.cast()).cast<Utf8>().toDartString()}');
    }
    var rc = ssh_scp_init(scp);
    if (rc != SSH_OK) {
      ssh_scp_free(scp);
      throw Exception(
          "Error initializing scp directory session: ${ssh_get_error(session.cast()).cast<Utf8>().toDartString()}");
    }
 do {
      rc = ssh_scp_pull_request(scp);
      if (exitLoop) {
        break;
      }
     switch (rc) {
        case ssh_scp_request_types.SSH_SCP_REQUEST_NEWFILE:
             var rawFilename = ssh_scp_request_get_filename(scp);
            //some way to tell if the file is a symbolic
             break;
         case SSH_ERROR:
        ...
        }
 }
.......
    } while (true);
```

https://github.com/insinfo/fsbackup

**Comment by Sibras** [comment]
Thats probably a question for the upstream libssh user help. This repo just deals with the msvc compilation of libssh, for more fundamental library questions your best bet is to ask upstream.

**Comment by insinfo** [comment]
do you know if this is the official repository?
https://gitlab.com/libssh/libssh-mirror
They don't seem to respond Issues

**Comment by Sibras** [comment]
> 
> 
> do you know if this is the official repository? https://gitlab.com/libssh/libssh-mirror They don't seem to respond Issues

No, that is a mirror (its in the name).

For details on how to ask questions see the official libssh homepage [https://www.libssh.org/communication/](https://www.libssh.org/communication/)
