### ISSUE TITLE
Which version of libssh supports SSH1 server?

### ISSUE THREAD

**Issue by Mr-LZG** [ShiftMediaProject/libssh#6]
## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used:
* Operating System and Version:
* Compiler and Version(s):

**Comment by Mr-LZG** [comment]
Which version of libssh supports SSH1 server?

**Comment by Sibras** [comment]
No idea, youll have to go back through the git history and check which release has SSH1 enabled in SMP/config.h

**Comment by Mr-LZG** [comment]
libssh0.7.7 supports SSH1, but I don't know how to write an SSH1 service with it. The  "ssh_server_fork" example also only supports SSH2。

**Comment by Mr-LZG** [comment]
> libssh0.7.7 supports SSH1, but I don't know how to write an SSH1 service with it. The "ssh_server_fork" example also only supports SSH2。

**Comment by Mr-LZG** [comment]
@Sibras libssh0.7.7 supports SSH1, but I don't know how to write an SSH1 service with it. The "ssh_server_fork" example also only supports SSH2。

**Comment by Sibras** [comment]
SSH1 has largely been deprecated due to security flaws.
Also any usage questions should be directed towards the upstream libssh user support as this project is only about Visual Studio compilation,

**Comment by Mr-LZG** [comment]
Ok, thanks
